package admin

import (
	"net/http"
	"strings"
	"time"
)

const (
	langRU = "ru"
	langEN = "en"
)

var translations = map[string]map[string]string{
	langRU: {
		"nav.connectors":    "Коннекторы",
		"nav.legal":         "Оферты",
		"nav.users":         "Пользователи",
		"nav.billing":       "Биллинг",
		"nav.churn":         "Проблемы",
		"nav.events":        "События",
		"nav.guide":         "Гайд",
		"nav.logout":        "Выйти",
		"lang.ru":           "Рус",
		"lang.en":           "Eng",
		"common.export_csv": "Экспорт CSV",
		"common.filters":    "Фильтры",
		"common.hint":       "Подсказка",

		"legal.title":                  "Оферты и документы",
		"legal.subtitle":               "Версионируемые юридические документы для онбординга и оплаты. Каждая версия доступна по своей публичной ссылке без авторизации; если у коннектора нет своих ссылок, бот использует активные версии отсюда.",
		"legal.create":                 "Новая версия документа",
		"legal.edit":                   "Редактирование документа",
		"legal.create_button":          "Сохранить версию",
		"legal.update_button":          "Сохранить изменения",
		"legal.cancel_edit":            "Отмена",
		"legal.table_title":            "Реестр документов",
		"legal.public.offer":           "Публичная ссылка оферты",
		"legal.public.privacy":         "Публичная ссылка политики",
		"legal.public.agreement":       "Публичная ссылка соглашения",
		"legal.required":               "Обязательные: тип, заголовок и хотя бы одно из полей Content / External URL.",
		"legal.created":                "версия документа создана",
		"legal.updated":                "документ обновлен",
		"legal.enabled":                "документ включен",
		"legal.disabled":               "документ выключен",
		"legal.deleted":                "документ удален",
		"legal.bad_form":               "не удалось разобрать форму документа",
		"legal.invalid_id":             "некорректный ID документа",
		"legal.load_error":             "не удалось загрузить реестр документов",
		"legal.validation.type":        "нужно выбрать тип документа",
		"legal.validation.title":       "нужно заполнить заголовок документа",
		"legal.validation.content":     "нужно заполнить текст документа или внешнюю ссылку",
		"legal.type.offer":             "Публичная оферта",
		"legal.type.privacy":           "Политика ПДн",
		"legal.type.user_agreement":    "Пользовательское соглашение",
		"legal.form.type":              "Тип документа *",
		"legal.form.title":             "Заголовок *",
		"legal.form.title_ph":          "Например, Публичная оферта от 20.03.2026",
		"legal.form.external_url":      "Внешняя ссылка",
		"legal.form.external_url_hint": "Если заполнено, публичная страница документа будет вести на этот внешний URL. Если пусто, пользователю показывается текст, сохраненный в поле документа.",
		"legal.form.content":           "Текст документа",
		"legal.form.content_ph":        "Если поле оставить пустым, пользователи будут открывать External URL.",
		"legal.form.is_active":         "Включить документ сразу",
		"legal.table.id":               "ID",
		"legal.table.type":             "Тип",
		"legal.table.version":          "Версия",
		"legal.table.title":            "Заголовок",
		"legal.table.preview":          "Превью",
		"legal.table.source":           "Источник",
		"legal.table.active":           "Статус",
		"legal.table.created":          "Создан",
		"legal.table.actions":          "Действия",
		"legal.table.open":             "Открыть",
		"legal.table.edit":             "Редактировать",
		"legal.table.enable":           "Включить",
		"legal.table.disable":          "Выключить",
		"legal.table.delete":           "Удалить",
		"legal.delete_confirm":         "Удалить документ? Это действие необратимо.",

		"login.title":        "Вход в админку",
		"login.subtitle":     "Введите ADMIN_AUTH_TOKEN для доступа к панели.",
		"login.token":        "Токен",
		"login.submit":       "Войти",
		"login.hint":         "Для локальной разработки используйте значение ADMIN_AUTH_TOKEN из .env.",
		"login.bad_form":     "не удалось разобрать форму",
		"login.bad_token":    "неверный токен",
		"login.rate_limited": "слишком много неудачных попыток, попробуйте позже",
		"csrf.invalid":       "сессия формы устарела, обновите страницу и попробуйте снова",

		"connectors.title":                 "Коннекторы",
		"connectors.subtitle":              "Коннектор - это тариф/условие оплаты, по которому пользователь приходит в бот.",
		"connectors.create":                "Создать коннектор",
		"connectors.hint_title":            "Подсказка",
		"connectors.table_title":           "Список коннекторов",
		"connectors.required":              "Обязательные: Name, Price RUB. Из пары Chat ID / Channel URL заполните хотя бы одно.",
		"connectors.created":               "коннектор создан",
		"connectors.updated":               "статус коннектора обновлен",
		"connectors.deleted":               "коннектор удален",
		"connectors.bad_form":              "не удалось разобрать форму",
		"connectors.invalid_id":            "некорректный ID коннектора",
		"connectors.not_found":             "коннектор не найден",
		"connectors.delete_in_use":         "коннектор нельзя удалить: он уже используется в истории платежей, подписок или регистраций",
		"connectors.delete_confirm":        "Удалить коннектор? Это действие необратимо.",
		"connector.validation.price":       "цена должна быть положительным числом",
		"connector.validation.period":      "период должен быть положительным числом",
		"connector.validation.chat_or_url": "нужно заполнить Chat ID или Channel URL",

		"connectors.form.name":           "Название *",
		"connectors.form.chat_id":        "Chat ID *",
		"connectors.form.price_rub":      "Цена RUB *",
		"connectors.form.period_days":    "Период (дней)",
		"connectors.form.start_payload":  "Start payload",
		"connectors.form.internal_id":    "Внутренний ID",
		"connectors.form.offer_url":      "Ссылка оферты",
		"connectors.form.privacy_url":    "Ссылка политики",
		"connectors.form.channel_url":    "Ссылка канала",
		"connectors.form.description":    "Описание",
		"connectors.form.description_ph": "Краткое описание тарифа",
		"connectors.form.price_ph":       "3335",
		"connectors.form.payload_hint":   "Если пусто, будет сгенерирован автоматически.",
		"connectors.form.id_hint":        "Если пусто, будет сгенерирован автоматически.",
		"connectors.required_short":      "Обязательные: Name, Price RUB. Из пары Chat ID / Channel URL заполните хотя бы одно.",

		"connectors.table.id":        "ID",
		"connectors.table.payload":   "Payload",
		"connectors.table.name":      "Название",
		"connectors.table.chat":      "Chat",
		"connectors.table.price":     "Цена",
		"connectors.table.period":    "Период",
		"connectors.table.offer":     "Оферта",
		"connectors.table.privacy":   "Политика",
		"connectors.table.channel":   "Канал",
		"connectors.table.bot_link":  "Ссылка бота",
		"connectors.table.open_link": "Открыть",
		"connectors.table.bot_open":  "Запуск",
		"connectors.table.active":    "Статус",
		"connectors.table.action":    "Действие",
		"connectors.table.enable":    "Включить",
		"connectors.table.disable":   "Выключить",
		"connectors.table.delete":    "Удалить",
		"badge.connector.active":     "активен",
		"badge.connector.inactive":   "выключен",
		"badge.payment.pending":      "ожидает",
		"badge.payment.paid":         "оплачен",
		"badge.payment.failed":       "ошибка",
		"badge.subscription.active":  "активна",
		"badge.subscription.expired": "истекла",
		"badge.subscription.revoked": "отключена",
		"badge.autopay.enabled":      "включен",
		"badge.autopay.disabled":     "выключен",
		"badge.autopay.unset":        "не настроен",

		"events.title":      "События аудита",
		"events.subtitle":   "Фильтрация, сортировка и пагинация действий пользователей.",
		"events.load_error": "не удалось загрузить события",
		"events.apply":      "Применить",
		"events.reset":      "Сброс",
		"events.total":      "Всего",
		"events.page":       "Страница",
		"events.first":      "Первая",
		"events.prev":       "Назад",
		"events.next":       "Вперед",
		"events.last":       "Последняя",

		"events.filter.telegram_id":  "Telegram ID",
		"events.filter.connector_id": "ID коннектора",
		"events.filter.action":       "Действие",
		"events.filter.search":       "Поиск в details",
		"events.filter.date_from":    "Дата от",
		"events.filter.date_to":      "Дата до",
		"events.filter.sort_by":      "Сортировка по",
		"events.filter.sort_dir":     "Направление",
		"events.filter.page_size":    "Размер страницы",
		"events.sort.asc":            "по возрастанию",
		"events.sort.desc":           "по убыванию",

		"events.table.time":        "Время",
		"events.table.telegram_id": "Telegram ID",
		"events.table.connector":   "Коннектор",
		"events.table.action":      "Действие",
		"events.table.details":     "Детали",

		"billing.title":                        "Платежи и подписки",
		"billing.subtitle":                     "Операционный срез по оплатам и выданным подпискам.",
		"billing.load_error":                   "не удалось загрузить платежи/подписки",
		"billing.apply":                        "Применить",
		"billing.reset":                        "Сброс",
		"billing.filter.telegram_id":           "Telegram ID",
		"billing.filter.connector_id":          "ID коннектора",
		"billing.filter.payment_status":        "Статус платежа",
		"billing.filter.subscription_status":   "Статус подписки",
		"billing.filter.date_from":             "Дата от",
		"billing.filter.date_to":               "Дата до",
		"billing.payment_status.any":           "Любой",
		"billing.payment_status.pending":       "pending",
		"billing.payment_status.paid":          "paid",
		"billing.payment_status.failed":        "failed",
		"billing.sub_status.any":               "Любой",
		"billing.sub_status.active":            "active",
		"billing.sub_status.expired":           "expired",
		"billing.sub_status.revoked":           "revoked",
		"billing.payments.title":               "Платежи",
		"billing.subscriptions.title":          "Подписки",
		"billing.summary.title":                "Сводка по выборке",
		"billing.summary.paid_amount":          "Оплачено",
		"billing.summary.pending_amount":       "Ожидает оплаты",
		"billing.summary.paid_payments":        "Успешных платежей",
		"billing.summary.failed_payments":      "Ошибок оплаты",
		"billing.summary.active_subscriptions": "Активных подписок",
		"billing.groups.title":                 "Итоги по коннекторам",
		"billing.groups.connector":             "Коннектор",
		"billing.groups.paid_amount":           "Оплачено",
		"billing.groups.paid_count":            "Успешно",
		"billing.groups.pending_count":         "В ожидании",
		"billing.groups.failed_count":          "Ошибки",
		"billing.groups.active_subscriptions":  "Активных подписок",
		"churn.title":                          "Проблемные оплаты и churn",
		"churn.subtitle":                       "Операционный список пользователей, у которых сломалась оплата, истек доступ или подписка была отключена.",
		"churn.filter.issue_type":              "Тип проблемы",
		"churn.filter.search":                  "Поиск",
		"churn.filter.search_ph":               "username, ФИО, email, телефон, коннектор",
		"churn.issue.any":                      "Любой",
		"churn.issue.failed_payment":           "Ошибка оплаты",
		"churn.issue.expired_subscription":     "Истекшая подписка",
		"churn.issue.revoked_subscription":     "Отключенная подписка",
		"churn.issue.pending_payment":          "Ожидающий платеж",
		"churn.table.user":                     "Пользователь",
		"churn.table.connector":                "Коннектор",
		"churn.table.issue":                    "Проблема",
		"churn.table.payment":                  "Платеж",
		"churn.table.subscription":             "Подписка",
		"churn.table.amount":                   "Сумма",
		"churn.table.last_event":               "Последнее событие",
		"churn.table.actions":                  "Действия",
		"billing.table.payment.id":             "ID",
		"billing.table.payment.provider":       "Провайдер",
		"billing.table.payment.status":         "Статус",
		"billing.table.payment.autopay":        "Автоплатеж",
		"billing.table.payment.telegram":       "Telegram",
		"billing.table.payment.connector":      "Коннектор",
		"billing.table.payment.amount":         "Сумма",
		"billing.table.payment.created":        "Создан",
		"billing.table.payment.paid_at":        "Оплачен",
		"billing.table.subscription.id":        "ID",
		"billing.table.subscription.status":    "Статус",
		"billing.table.subscription.autopay":   "Автоплатеж",
		"billing.table.subscription.telegram":  "Telegram",
		"billing.table.subscription.connector": "Коннектор",
		"billing.table.subscription.payment":   "Платеж",
		"billing.table.subscription.starts":    "Начало",
		"billing.table.subscription.ends":      "Окончание",
		"billing.table.subscription.created":   "Создана",

		"users.title":                                "Пользователи",
		"users.subtitle":                             "Реестр пользователей, собранных ботом во время регистрации и оплат.",
		"users.load_error":                           "не удалось загрузить пользователей",
		"users.apply":                                "Применить",
		"users.reset":                                "Сброс",
		"users.filter.telegram_id":                   "Telegram ID",
		"users.filter.search":                        "Поиск",
		"users.filter.search_ph":                     "username, ФИО, email, телефон",
		"users.table.id":                             "Telegram ID",
		"users.table.username":                       "Username",
		"users.table.full_name":                      "ФИО",
		"users.table.phone":                          "Телефон",
		"users.table.email":                          "E-mail",
		"users.table.autopay":                        "Автоплатеж",
		"users.table.updated":                        "Обновлен",
		"users.autopay.enabled":                      "включен",
		"users.autopay.disabled":                     "выключен",
		"users.autopay.not_configured":               "не настроен",
		"users.detail.back":                          "Назад к списку",
		"users.detail.profile":                       "Профиль",
		"users.detail.payments":                      "Платежи",
		"users.detail.subscriptions":                 "Подписки",
		"users.detail.consents":                      "Согласия",
		"users.detail.recurring_consents":            "Согласия на автосписания",
		"users.detail.events":                        "События",
		"users.detail.load_error":                    "не удалось загрузить карточку пользователя",
		"users.detail.not_found":                     "пользователь не найден",
		"users.detail.invalid_id":                    "некорректный Telegram ID пользователя",
		"users.detail.empty":                         "данных пока нет",
		"users.revoke.action":                        "Действие",
		"users.revoke.button":                        "Отключить",
		"users.revoke.confirm":                       "Отключить подписку пользователю вручную?",
		"users.revoke.success":                       "подписка отключена вручную",
		"users.revoke.failed":                        "не удалось отключить подписку",
		"users.revoke.not_found":                     "подписка не найдена",
		"users.revoke.only_active":                   "вручную можно отключить только активную подписку",
		"users.revoke.notify":                        "Подписка была отключена администратором.",
		"users.revoke.notify_with_connector":         "Подписка «%s» была отключена администратором.",
		"users.revoke.renew":                         "Оформить заново",
		"users.actions.title":                        "Действия",
		"users.actions.message":                      "Сообщение пользователю",
		"users.actions.message_ph":                   "Введите текст, который нужно отправить пользователю",
		"users.actions.message_send":                 "Отправить сообщение",
		"users.actions.paylink":                      "Ссылка на оплату",
		"users.actions.paylink_send":                 "Отправить ссылку",
		"users.actions.message_empty":                "сообщение не должно быть пустым",
		"users.actions.message_sent":                 "сообщение отправлено пользователю",
		"users.actions.paylink_sent":                 "ссылка на оплату отправлена пользователю",
		"users.actions.paylink_unavailable":          "для этой подписки недоступна ссылка на оплату",
		"users.actions.paylink_text":                 "Чтобы продлить или оформить доступ заново, нажмите кнопку ниже.",
		"users.actions.paylink_text_named":           "Чтобы продлить подписку «%s» или оформить ее заново, нажмите кнопку ниже.",
		"users.actions.paylink_button":               "Оплатить подписку",
		"users.actions.paylink_hint":                 "Кнопка отправки ссылки доступна в таблице подписок для каждого конкретного коннектора.",
		"users.consents.offer_accepted":              "Оферта принята",
		"users.consents.offer_version":               "Версия оферты",
		"users.consents.privacy_accepted":            "Политика принята",
		"users.consents.privacy_version":             "Версия политики",
		"users.consents.custom":                      "внешняя ссылка / custom",
		"users.consents.version_prefix":              "версия",
		"users.recurring_consents.accepted_at":       "Принято",
		"users.recurring_consents.offer_version":     "Оферта",
		"users.recurring_consents.agreement_version": "Соглашение",
		"users.recurring.summary_title":              "Сводка по автоплатежу",
		"users.recurring.summary_status":             "Статус автоплатежа",
		"users.recurring.summary_last_at":            "Последний opt-in",
		"users.recurring.summary_last_connector":     "Последний коннектор",
		"users.recurring.summary_health":             "Состояние",
		"users.recurring.health_no_consent":          "согласий нет",
		"users.recurring.health_missing_consent":     "включен без consent",
		"users.recurring.health_consistent":          "данные консистентны",
		"users.recurring.health_disabled":            "отключен пользователем",

		"guide.title": "Гайд по админке",
		"guide.s1":    "1. Как создать коннектор",
		"guide.s1.p":  "Заполните Name, Chat ID и Price RUB. Нажмите кнопку создания.",
		"guide.s2":    "2. Поля формы",
		"guide.s2.p1": "Name: название тарифа, которое увидит пользователь.",
		"guide.s2.p2": "Chat ID: Telegram ID чата/канала в формате без минуса, например 1003626584986.",
		"guide.s2.p3": "Price RUB: сумма оплаты в рублях.",
		"guide.s2.p4": "Period days: длительность подписки в днях (по умолчанию 30).",
		"guide.s2.p5": "Start payload: токен deeplink (/start ...). Если пусто, генерируется автоматически.",
		"guide.s2.p6": "ID коннектора: автоинкрементный числовой ID в БД, заполнять вручную не нужно.",
		"guide.s2.p7": "Offer URL, Privacy URL и Channel URL: ссылки на оферту, политику ПДн и канал для перехода после оплаты.",
		"guide.s2.p8": "Description: дополнительное описание тарифа.",
		"guide.s3":    "3. Как тестировать",
		"guide.s3.p1": "Скопируйте Bot Link из таблицы и откройте его в Telegram. Пройдите диалог и нажмите «Оплатить».",
		"guide.s3.p2": "Пока активен mock-провайдер, откроется тестовая страница оплаты.",
	},
	langEN: {
		"nav.connectors":    "Connectors",
		"nav.legal":         "Legal",
		"nav.users":         "Users",
		"nav.billing":       "Billing",
		"nav.churn":         "Churn",
		"nav.events":        "Events",
		"nav.guide":         "Guide",
		"nav.logout":        "Logout",
		"lang.ru":           "Rus",
		"lang.en":           "Eng",
		"common.export_csv": "Export CSV",
		"common.filters":    "Filters",
		"common.hint":       "Hint",

		"legal.title":                  "Legal documents",
		"legal.subtitle":               "Versioned legal documents used during onboarding and checkout. Each version has its own public URL without auth; if connector links are empty, bot falls back to active documents from this registry.",
		"legal.create":                 "New document version",
		"legal.edit":                   "Edit document",
		"legal.create_button":          "Save version",
		"legal.update_button":          "Save changes",
		"legal.cancel_edit":            "Cancel",
		"legal.table_title":            "Documents registry",
		"legal.public.offer":           "Public offer URL",
		"legal.public.privacy":         "Public privacy URL",
		"legal.public.agreement":       "Public agreement URL",
		"legal.required":               "Required: document type, title, and at least one of Content / External URL.",
		"legal.created":                "document version created",
		"legal.updated":                "document updated",
		"legal.enabled":                "document enabled",
		"legal.disabled":               "document disabled",
		"legal.deleted":                "document deleted",
		"legal.bad_form":               "failed to parse document form",
		"legal.invalid_id":             "invalid document ID",
		"legal.load_error":             "failed to load legal documents",
		"legal.validation.type":        "document type is required",
		"legal.validation.title":       "document title is required",
		"legal.validation.content":     "either document content or external URL is required",
		"legal.type.offer":             "Public offer",
		"legal.type.privacy":           "Privacy policy",
		"legal.type.user_agreement":    "User agreement",
		"legal.form.type":              "Document type *",
		"legal.form.title":             "Title *",
		"legal.form.title_ph":          "For example, Public offer dated 2026-03-20",
		"legal.form.external_url":      "External URL",
		"legal.form.external_url_hint": "If filled, public document page redirects users to this external URL. If empty, users see the saved document text.",
		"legal.form.content":           "Document content",
		"legal.form.content_ph":        "Leave empty if users should be redirected to External URL.",
		"legal.form.is_active":         "Enable document immediately",
		"legal.table.id":               "ID",
		"legal.table.type":             "Type",
		"legal.table.version":          "Version",
		"legal.table.title":            "Title",
		"legal.table.preview":          "Preview",
		"legal.table.source":           "Source",
		"legal.table.active":           "Status",
		"legal.table.created":          "Created",
		"legal.table.actions":          "Actions",
		"legal.table.open":             "Open",
		"legal.table.edit":             "Edit",
		"legal.table.enable":           "Enable",
		"legal.table.disable":          "Disable",
		"legal.table.delete":           "Delete",
		"legal.delete_confirm":         "Delete document? This action cannot be undone.",

		"login.title":        "Admin login",
		"login.subtitle":     "Enter ADMIN_AUTH_TOKEN to access admin panel.",
		"login.token":        "Token",
		"login.submit":       "Sign in",
		"login.hint":         "For local development use ADMIN_AUTH_TOKEN value from .env.",
		"login.bad_form":     "failed to parse form",
		"login.bad_token":    "invalid token",
		"login.rate_limited": "too many failed attempts, try again later",
		"csrf.invalid":       "form session expired, refresh page and try again",

		"connectors.title":                 "Connectors",
		"connectors.subtitle":              "Connector defines tariff/payment conditions used in bot deep links.",
		"connectors.create":                "Create connector",
		"connectors.hint_title":            "Hint",
		"connectors.table_title":           "Connectors list",
		"connectors.required":              "Required: Name, Price RUB. Fill at least one of Chat ID / Channel URL.",
		"connectors.created":               "connector created",
		"connectors.updated":               "connector status updated",
		"connectors.deleted":               "connector deleted",
		"connectors.bad_form":              "failed to parse form",
		"connectors.invalid_id":            "invalid connector ID",
		"connectors.not_found":             "connector not found",
		"connectors.delete_in_use":         "connector cannot be deleted because it already has payment, subscription or registration history",
		"connectors.delete_confirm":        "Delete connector? This action cannot be undone.",
		"connector.validation.price":       "price must be a positive number",
		"connector.validation.period":      "period must be a positive number",
		"connector.validation.chat_or_url": "either Chat ID or Channel URL is required",

		"connectors.form.name":           "Name *",
		"connectors.form.chat_id":        "Chat ID *",
		"connectors.form.price_rub":      "Price RUB *",
		"connectors.form.period_days":    "Period days",
		"connectors.form.start_payload":  "Start payload",
		"connectors.form.internal_id":    "Internal ID",
		"connectors.form.offer_url":      "Offer URL",
		"connectors.form.privacy_url":    "Privacy URL",
		"connectors.form.channel_url":    "Channel URL",
		"connectors.form.description":    "Description",
		"connectors.form.description_ph": "Short tariff description",
		"connectors.form.price_ph":       "3335",
		"connectors.form.payload_hint":   "Auto-generated if empty.",
		"connectors.form.id_hint":        "Auto-generated if empty.",
		"connectors.required_short":      "Required: Name, Price RUB. Fill at least one of Chat ID / Channel URL.",

		"connectors.table.id":        "ID",
		"connectors.table.payload":   "Payload",
		"connectors.table.name":      "Name",
		"connectors.table.chat":      "Chat",
		"connectors.table.price":     "Price",
		"connectors.table.period":    "Period",
		"connectors.table.offer":     "Offer",
		"connectors.table.privacy":   "Privacy",
		"connectors.table.channel":   "Channel",
		"connectors.table.bot_link":  "Bot link",
		"connectors.table.open_link": "Open",
		"connectors.table.bot_open":  "Launch",
		"connectors.table.active":    "Status",
		"connectors.table.action":    "Action",
		"connectors.table.enable":    "Enable",
		"connectors.table.disable":   "Disable",
		"connectors.table.delete":    "Delete",
		"badge.connector.active":     "active",
		"badge.connector.inactive":   "disabled",
		"badge.payment.pending":      "pending",
		"badge.payment.paid":         "paid",
		"badge.payment.failed":       "failed",
		"badge.subscription.active":  "active",
		"badge.subscription.expired": "expired",
		"badge.subscription.revoked": "revoked",
		"badge.autopay.enabled":      "enabled",
		"badge.autopay.disabled":     "disabled",
		"badge.autopay.unset":        "not configured",

		"events.title":      "Audit events",
		"events.subtitle":   "Filter, sort and paginate user actions.",
		"events.load_error": "failed to load events",
		"events.apply":      "Apply",
		"events.reset":      "Reset",
		"events.total":      "Total",
		"events.page":       "Page",
		"events.first":      "First",
		"events.prev":       "Prev",
		"events.next":       "Next",
		"events.last":       "Last",

		"events.filter.telegram_id":  "Telegram ID",
		"events.filter.connector_id": "Connector ID",
		"events.filter.action":       "Action",
		"events.filter.search":       "Search in details",
		"events.filter.date_from":    "Date from",
		"events.filter.date_to":      "Date to",
		"events.filter.sort_by":      "Sort by",
		"events.filter.sort_dir":     "Sort dir",
		"events.filter.page_size":    "Page size",
		"events.sort.asc":            "ascending",
		"events.sort.desc":           "descending",

		"events.table.time":        "Time",
		"events.table.telegram_id": "Telegram ID",
		"events.table.connector":   "Connector",
		"events.table.action":      "Action",
		"events.table.details":     "Details",

		"billing.title":                        "Payments and subscriptions",
		"billing.subtitle":                     "Operational view of payment attempts and granted subscriptions.",
		"billing.load_error":                   "failed to load payments/subscriptions",
		"billing.apply":                        "Apply",
		"billing.reset":                        "Reset",
		"billing.filter.telegram_id":           "Telegram ID",
		"billing.filter.connector_id":          "Connector ID",
		"billing.filter.payment_status":        "Payment status",
		"billing.filter.subscription_status":   "Subscription status",
		"billing.filter.date_from":             "Date from",
		"billing.filter.date_to":               "Date to",
		"billing.payment_status.any":           "Any",
		"billing.payment_status.pending":       "pending",
		"billing.payment_status.paid":          "paid",
		"billing.payment_status.failed":        "failed",
		"billing.sub_status.any":               "Any",
		"billing.sub_status.active":            "active",
		"billing.sub_status.expired":           "expired",
		"billing.sub_status.revoked":           "revoked",
		"billing.payments.title":               "Payments",
		"billing.subscriptions.title":          "Subscriptions",
		"billing.summary.title":                "Selection summary",
		"billing.summary.paid_amount":          "Paid amount",
		"billing.summary.pending_amount":       "Pending amount",
		"billing.summary.paid_payments":        "Successful payments",
		"billing.summary.failed_payments":      "Failed payments",
		"billing.summary.active_subscriptions": "Active subscriptions",
		"billing.groups.title":                 "Connector totals",
		"billing.groups.connector":             "Connector",
		"billing.groups.paid_amount":           "Paid amount",
		"billing.groups.paid_count":            "Successful",
		"billing.groups.pending_count":         "Pending",
		"billing.groups.failed_count":          "Failed",
		"billing.groups.active_subscriptions":  "Active subscriptions",
		"churn.title":                          "Problem payments and churn",
		"churn.subtitle":                       "Operational list of users with broken payments, expired access or manually revoked subscriptions.",
		"churn.filter.issue_type":              "Issue type",
		"churn.filter.search":                  "Search",
		"churn.filter.search_ph":               "username, full name, email, phone, connector",
		"churn.issue.any":                      "Any",
		"churn.issue.failed_payment":           "Failed payment",
		"churn.issue.expired_subscription":     "Expired subscription",
		"churn.issue.revoked_subscription":     "Revoked subscription",
		"churn.issue.pending_payment":          "Pending payment",
		"churn.table.user":                     "User",
		"churn.table.connector":                "Connector",
		"churn.table.issue":                    "Issue",
		"churn.table.payment":                  "Payment",
		"churn.table.subscription":             "Subscription",
		"churn.table.amount":                   "Amount",
		"churn.table.last_event":               "Last event",
		"churn.table.actions":                  "Actions",
		"billing.table.payment.id":             "ID",
		"billing.table.payment.provider":       "Provider",
		"billing.table.payment.status":         "Status",
		"billing.table.payment.autopay":        "Autopay",
		"billing.table.payment.telegram":       "Telegram",
		"billing.table.payment.connector":      "Connector",
		"billing.table.payment.amount":         "Amount",
		"billing.table.payment.created":        "Created",
		"billing.table.payment.paid_at":        "Paid at",
		"billing.table.subscription.id":        "ID",
		"billing.table.subscription.status":    "Status",
		"billing.table.subscription.autopay":   "Autopay",
		"billing.table.subscription.telegram":  "Telegram",
		"billing.table.subscription.connector": "Connector",
		"billing.table.subscription.payment":   "Payment",
		"billing.table.subscription.starts":    "Starts",
		"billing.table.subscription.ends":      "Ends",
		"billing.table.subscription.created":   "Created",

		"users.title":                                "Users",
		"users.subtitle":                             "Registry of users collected by the bot during registration and payments.",
		"users.load_error":                           "failed to load users",
		"users.apply":                                "Apply",
		"users.reset":                                "Reset",
		"users.filter.telegram_id":                   "Telegram ID",
		"users.filter.search":                        "Search",
		"users.filter.search_ph":                     "username, full name, email, phone",
		"users.table.id":                             "Telegram ID",
		"users.table.username":                       "Username",
		"users.table.full_name":                      "Full name",
		"users.table.phone":                          "Phone",
		"users.table.email":                          "E-mail",
		"users.table.autopay":                        "Autopay",
		"users.table.updated":                        "Updated",
		"users.autopay.enabled":                      "enabled",
		"users.autopay.disabled":                     "disabled",
		"users.autopay.not_configured":               "not configured",
		"users.detail.back":                          "Back to list",
		"users.detail.profile":                       "Profile",
		"users.detail.payments":                      "Payments",
		"users.detail.subscriptions":                 "Subscriptions",
		"users.detail.consents":                      "Consents",
		"users.detail.recurring_consents":            "Recurring consents",
		"users.detail.events":                        "Events",
		"users.detail.load_error":                    "failed to load user card",
		"users.detail.not_found":                     "user not found",
		"users.detail.invalid_id":                    "invalid user Telegram ID",
		"users.detail.empty":                         "no data yet",
		"users.revoke.action":                        "Action",
		"users.revoke.button":                        "Disable",
		"users.revoke.confirm":                       "Disable this subscription manually?",
		"users.revoke.success":                       "subscription disabled manually",
		"users.revoke.failed":                        "failed to disable subscription",
		"users.revoke.not_found":                     "subscription not found",
		"users.revoke.only_active":                   "only active subscription can be disabled manually",
		"users.revoke.notify":                        "Your subscription was disabled by the administrator.",
		"users.revoke.notify_with_connector":         "Your subscription \"%s\" was disabled by the administrator.",
		"users.revoke.renew":                         "Renew access",
		"users.actions.title":                        "Actions",
		"users.actions.message":                      "Message user",
		"users.actions.message_ph":                   "Enter text to send to the user",
		"users.actions.message_send":                 "Send message",
		"users.actions.paylink":                      "Payment link",
		"users.actions.paylink_send":                 "Send link",
		"users.actions.message_empty":                "message cannot be empty",
		"users.actions.message_sent":                 "message sent to user",
		"users.actions.paylink_sent":                 "payment link sent to user",
		"users.actions.paylink_unavailable":          "payment link is unavailable for this subscription",
		"users.actions.paylink_text":                 "To renew or purchase access again, use the button below.",
		"users.actions.paylink_text_named":           "To renew subscription \"%s\" or purchase it again, use the button below.",
		"users.actions.paylink_button":               "Pay subscription",
		"users.actions.paylink_hint":                 "Payment-link sending is available in the subscriptions table for each connector.",
		"users.consents.offer_accepted":              "Offer accepted",
		"users.consents.offer_version":               "Offer version",
		"users.consents.privacy_accepted":            "Privacy accepted",
		"users.consents.privacy_version":             "Privacy version",
		"users.consents.custom":                      "external URL / custom",
		"users.consents.version_prefix":              "version",
		"users.recurring_consents.accepted_at":       "Accepted at",
		"users.recurring_consents.offer_version":     "Offer",
		"users.recurring_consents.agreement_version": "Agreement",
		"users.recurring.summary_title":              "Recurring summary",
		"users.recurring.summary_status":             "Autopay status",
		"users.recurring.summary_last_at":            "Last opt-in",
		"users.recurring.summary_last_connector":     "Last connector",
		"users.recurring.summary_health":             "Health",
		"users.recurring.health_no_consent":          "no consents",
		"users.recurring.health_missing_consent":     "enabled without consent",
		"users.recurring.health_consistent":          "data is consistent",
		"users.recurring.health_disabled":            "disabled by user",

		"guide.title": "Admin guide",
		"guide.s1":    "1. How to create connector",
		"guide.s1.p":  "Fill Name, Chat ID and Price RUB. Click create button.",
		"guide.s2":    "2. Form fields",
		"guide.s2.p1": "Name: tariff name visible to users.",
		"guide.s2.p2": "Chat ID: chat/channel Telegram ID without minus, e.g. 1003626584986.",
		"guide.s2.p3": "Price RUB: payment amount in RUB.",
		"guide.s2.p4": "Period days: subscription duration in days (default 30).",
		"guide.s2.p5": "Start payload: deeplink token (/start ...). Auto-generated when empty.",
		"guide.s2.p6": "Connector ID: auto-increment numeric ID in DB, no manual input needed.",
		"guide.s2.p7": "Offer URL, Privacy URL and Channel URL: links to legal docs and destination channel after payment.",
		"guide.s2.p8": "Description: additional tariff description.",
		"guide.s3":    "3. How to test",
		"guide.s3.p1": "Copy Bot Link from table, open in Telegram, complete flow and click Pay.",
		"guide.s3.p2": "While mock provider is enabled, test checkout page will be opened.",
	},
}

func (h *Handler) resolveLang(w http.ResponseWriter, r *http.Request) string {
	lang := normalizeLang(r.URL.Query().Get("lang"))
	if lang != "" {
		h.setCookie(w, r, http.Cookie{
			Name:     "admin_lang",
			Value:    lang,
			Path:     "/",
			HttpOnly: false,
			SameSite: http.SameSiteLaxMode,
			MaxAge:   int((30 * 24 * time.Hour).Seconds()),
		})
		return lang
	}
	if c, err := r.Cookie("admin_lang"); err == nil {
		if normalized := normalizeLang(c.Value); normalized != "" {
			return normalized
		}
	}
	return langRU
}

func normalizeLang(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case langEN:
		return langEN
	case langRU:
		return langRU
	default:
		return ""
	}
}

func dictForLang(lang string) map[string]string {
	if d, ok := translations[lang]; ok {
		return d
	}
	return translations[langRU]
}

func t(lang, key string) string {
	d := dictForLang(lang)
	if v, ok := d[key]; ok {
		return v
	}
	if v, ok := translations[langRU][key]; ok {
		return v
	}
	return key
}
