package admin

import (
	"net/http"
	"strings"
	"time"
)

const (
	langRU = "ru"
	langEN = "en"
)

var translations = map[string]map[string]string{
	langRU: {
		"nav.connectors":    "Коннекторы",
		"nav.legal":         "Документы",
		"nav.users":         "Пользователи",
		"nav.billing":       "Биллинг",
		"nav.churn":         "Проблемы",
		"nav.events":        "События",
		"nav.sessions":      "Сессии",
		"nav.guide":         "Справка",
		"nav.logout":        "Выйти",
		"lang.ru":           "Рус",
		"lang.en":           "Анг",
		"common.export_csv": "Экспорт CSV",
		"common.filters":    "Фильтры",
		"common.hint":       "Подсказка",
		"common.summary":    "Сводка",
		"common.breakdown":  "Разбивка",
		"common.registry":   "Реестр",
		"common.operations": "Операции",
		"common.security":   "Безопасность",
		"common.versioning": "Версии",
		"common.catalogue":  "Каталог",
		"common.audit":      "Аудит",
		"common.contacts":   "Контакты",
		"common.access":     "Доступ",
		"common.money":      "Платежи",
		"common.legal":      "Документы",
		"common.autopay":    "Автоплатеж",

		"legal.title":                  "Оферты и документы",
		"legal.subtitle":               "Версионируемые юридические документы для онбординга и оплаты. Каждая версия доступна по своей публичной ссылке без авторизации; если у коннектора нет своих ссылок, бот использует активные версии отсюда.",
		"legal.create":                 "Новая версия документа",
		"legal.edit":                   "Редактирование документа",
		"legal.create_button":          "Сохранить версию",
		"legal.update_button":          "Сохранить изменения",
		"legal.cancel_edit":            "Отмена",
		"legal.table_title":            "Реестр документов",
		"legal.public.offer":           "Публичная ссылка оферты",
		"legal.public.privacy":         "Публичная ссылка политики",
		"legal.public.agreement":       "Публичная ссылка соглашения",
		"legal.required":               "Обязательные поля: тип, заголовок и хотя бы одно из полей «Текст документа» или «Внешняя ссылка».",
		"legal.created":                "версия документа создана",
		"legal.updated":                "документ обновлен",
		"legal.enabled":                "документ включен",
		"legal.disabled":               "документ выключен",
		"legal.deleted":                "документ удален",
		"legal.bad_form":               "не удалось разобрать форму документа",
		"legal.invalid_id":             "некорректный ID документа",
		"legal.load_error":             "не удалось загрузить реестр документов",
		"legal.validation.type":        "нужно выбрать тип документа",
		"legal.validation.title":       "нужно заполнить заголовок документа",
		"legal.validation.content":     "нужно заполнить текст документа или внешнюю ссылку",
		"legal.type.offer":             "Публичная оферта",
		"legal.type.privacy":           "Политика ПДн",
		"legal.type.user_agreement":    "Пользовательское соглашение",
		"legal.form.type":              "Тип документа *",
		"legal.form.title":             "Заголовок *",
		"legal.form.title_ph":          "Например, Публичная оферта от 20.03.2026",
		"legal.form.external_url":      "Внешняя ссылка",
		"legal.form.external_url_hint": "Если заполнено, публичная страница документа будет вести на этот внешний URL. Если пусто, пользователю показывается текст, сохраненный в поле документа.",
		"legal.form.content":           "Текст документа",
		"legal.form.content_ph":        "Если поле оставить пустым, пользователи будут переходить по внешней ссылке.",
		"legal.form.is_active":         "Включить документ сразу",
		"legal.table.id":               "ID",
		"legal.table.type":             "Тип",
		"legal.table.version":          "Версия",
		"legal.table.title":            "Заголовок",
		"legal.table.preview":          "Превью",
		"legal.table.source":           "Источник",
		"legal.table.active":           "Статус",
		"legal.table.created":          "Создан",
		"legal.table.actions":          "Действия",
		"legal.table.open":             "Открыть",
		"legal.table.edit":             "Редактировать",
		"legal.table.enable":           "Включить",
		"legal.table.disable":          "Выключить",
		"legal.table.delete":           "Удалить",
		"legal.delete_confirm":         "Удалить документ? Это действие необратимо.",

		"login.title":               "Вход в админку",
		"login.subtitle":            "Введите ADMIN_AUTH_TOKEN для доступа к панели.",
		"login.token":               "Токен",
		"login.submit":              "Войти",
		"login.hint":                "Для локальной разработки используйте значение ADMIN_AUTH_TOKEN из .env.",
		"login.bad_form":            "не удалось разобрать форму",
		"login.bad_token":           "неверный токен",
		"login.rate_limited":        "слишком много неудачных попыток, попробуйте позже",
		"sessions.title":            "Активные сессии",
		"sessions.subtitle":         "Операционный список браузерных admin-сессий. Можно вручную завершить подозрительную или зависшую сессию.",
		"sessions.current":          "текущая",
		"sessions.revoke":           "Завершить",
		"sessions.revoked":          "сессия завершена",
		"sessions.load_error":       "не удалось загрузить список сессий",
		"sessions.invalid_id":       "некорректный ID сессии",
		"sessions.status.active":    "активна",
		"sessions.status.revoked":   "отозвана",
		"sessions.status.expired":   "истекла",
		"sessions.table.id":         "ID",
		"sessions.table.subject":    "Источник",
		"sessions.table.ip":         "IP",
		"sessions.table.user_agent": "User-Agent",
		"sessions.table.created":    "Создана",
		"sessions.table.expires":    "Истекает",
		"sessions.table.last_seen":  "Последняя активность",
		"sessions.table.status":     "Статус",
		"sessions.table.actions":    "Действия",
		"csrf.invalid":              "сессия формы устарела, обновите страницу и попробуйте снова",

		"connectors.title":                     "Коннекторы",
		"connectors.subtitle":                  "Коннектор - это тариф/условие оплаты, по которому пользователь приходит в бот.",
		"connectors.create":                    "Создать коннектор",
		"connectors.hint_title":                "Подсказка",
		"connectors.table_title":               "Список коннекторов",
		"connectors.required":                  "Обязательные поля: название и цена. Заполните хотя бы одно направление доступа.",
		"connectors.created":                   "коннектор создан",
		"connectors.updated":                   "статус коннектора обновлен",
		"connectors.deleted":                   "коннектор удален",
		"connectors.bad_form":                  "не удалось разобрать форму",
		"connectors.invalid_id":                "некорректный ID коннектора",
		"connectors.not_found":                 "коннектор не найден",
		"connectors.delete_in_use":             "коннектор нельзя удалить: он уже используется в истории платежей, подписок или регистраций",
		"connectors.delete_confirm":            "Удалить коннектор? Это действие необратимо.",
		"connector.validation.price":           "цена должна быть положительным числом",
		"connector.validation.period_mode":     "нужно выбрать тип периода",
		"connector.validation.period_duration": "длительность должна быть в формате 90s, 15m, 12h или 30d",
		"connector.validation.period_months":   "количество месяцев должно быть положительным числом",
		"connector.validation.period_deadline": "дедлайн должен быть в будущем и в формате дата/время",
		"connector.validation.chat_or_url":     "нужно заполнить хотя бы одно направление доступа: Telegram Chat ID, MAX Chat ID, Telegram Channel URL или MAX Channel URL",

		"connectors.form.name":                        "Название *",
		"connectors.form.chat_id":                     "Telegram Chat ID",
		"connectors.form.max_chat_id":                 "MAX Chat ID",
		"connectors.form.price_rub":                   "Цена, ₽ *",
		"connectors.form.period_mode":                 "Тип периода",
		"connectors.form.period_mode_duration":        "Длительность",
		"connectors.form.period_mode_calendar_months": "Календарные месяцы",
		"connectors.form.period_mode_fixed_deadline":  "До даты",
		"connectors.form.period_value":                "Длительность",
		"connectors.form.period_value_hint":           "Например: 120s, 15m, 12h, 30d.",
		"connectors.form.period_months":               "Количество месяцев",
		"connectors.form.period_months_hint":          "Например: 1, 3, 12.",
		"connectors.form.fixed_ends_at":               "Дата окончания",
		"connectors.form.fixed_ends_at_hint":          "Абсолютный дедлайн доступа. Автоплатеж для такого тарифа отключен.",
		"connectors.form.start_payload":               "Код запуска",
		"connectors.form.internal_id":                 "Внутренний ID",
		"connectors.form.offer_url":                   "Ссылка оферты",
		"connectors.form.privacy_url":                 "Ссылка политики",
		"connectors.form.channel_url":                 "Ссылка на Telegram-канал",
		"connectors.form.max_channel_url":             "Ссылка на MAX-канал",
		"connectors.form.description":                 "Описание",
		"connectors.form.description_ph":              "Краткое описание тарифа",
		"connectors.form.price_ph":                    "3335",
		"connectors.form.channel_hint":                "Публичная ссылка или @username для Telegram-доступа после оплаты.",
		"connectors.form.max_chat_id_hint":            "Явный ID MAX-чата для автоматического удаления и возврата участников. Если пусто, система попробует извлечь его из ссылки на MAX-канал.",
		"connectors.form.max_channel_hint":            "Публичная ссылка MAX для MAX-пользователей после оплаты.",
		"connectors.form.advanced":                    "Дополнительные настройки",
		"connectors.form.advanced_hint":               "Технические и редко используемые поля: ID чата, код запуска, юридические ссылки и описание.",
		"connectors.form.preview":                     "Превью ссылок запуска",
		"connectors.form.preview_pending":             "Если код запуска пустой, он будет сгенерирован автоматически при сохранении.",
		"connectors.form.preview_command":             "Команда MAX",
		"connectors.form.payload_hint":                "Если пусто, будет сгенерирован автоматически.",
		"connectors.form.id_hint":                     "Если пусто, будет сгенерирован автоматически.",
		"connectors.required_short":                   "Обязательные поля: название и цена. Заполните хотя бы одно направление доступа: Telegram Chat ID, MAX Chat ID, Telegram Channel URL или MAX Channel URL.",

		"connectors.table.id":                "ID",
		"connectors.table.payload":           "Код запуска",
		"connectors.table.name":              "Название",
		"connectors.table.chat":              "Telegram Chat",
		"connectors.table.max_chat_id":       "MAX Chat ID",
		"connectors.table.price":             "Цена",
		"connectors.table.period":            "Период",
		"connectors.table.offer":             "Оферта",
		"connectors.table.privacy":           "Политика",
		"connectors.table.channel":           "Направления доступа",
		"connectors.table.telegram_channel":  "Telegram",
		"connectors.table.max_channel":       "MAX",
		"connectors.table.legal":             "Документы",
		"connectors.table.launch":            "Запуск",
		"connectors.table.bot_link":          "Ссылки запуска",
		"connectors.table.telegram_bot_link": "Telegram",
		"connectors.table.max_bot_link":      "MAX",
		"connectors.table.max_start_command": "Команда MAX",
		"connectors.table.open_link":         "Открыть",
		"connectors.table.bot_open":          "Запуск",
		"connectors.table.active":            "Статус",
		"connectors.table.action":            "Действие",
		"connectors.table.enable":            "Включить",
		"connectors.table.disable":           "Выключить",
		"connectors.table.delete":            "Удалить",
		"badge.connector.active":             "активен",
		"badge.connector.inactive":           "выключен",
		"badge.payment.pending":              "ожидает",
		"badge.payment.paid":                 "оплачен",
		"badge.payment.failed":               "ошибка",
		"badge.subscription.active":          "активна",
		"badge.subscription.future":          "следующий период",
		"badge.subscription.expired":         "истекла",
		"badge.subscription.revoked":         "отключена",
		"badge.autopay.enabled":              "включен",
		"badge.autopay.disabled":             "выключен",
		"badge.autopay.unset":                "не настроен",
		"badge.ops.access_ready":             "доступ выдан",
		"badge.ops.access_issue":             "проблема доступа",
		"badge.ops.next_period":              "ожидает начала",
		"badge.ops.not_checked":              "нужна проверка",
		"badge.ops.not_applicable":           "не применимо",
		"badge.ops.retry_scheduled":          "повтор через backoff",
		"badge.ops.manual_check":             "нужна ручная проверка",
		"badge.ops.revoked":                  "удален из канала",
		"badge.ops.replacement_active":       "есть продление",

		"events.title":      "События аудита",
		"events.subtitle":   "Фильтрация, сортировка и пагинация действий пользователей.",
		"events.load_error": "не удалось загрузить события",
		"events.apply":      "Применить",
		"events.reset":      "Сброс",
		"events.filter.any": "Любой",
		"events.total":      "Всего",
		"events.page":       "Страница",
		"events.first":      "Первая",
		"events.prev":       "Назад",
		"events.next":       "Вперед",
		"events.last":       "Последняя",

		"events.filter.messenger_kind":    "Мессенджер",
		"events.filter.actor_type":        "Источник",
		"events.filter.messenger_user_id": "ID пользователя мессенджера",
		"events.filter.connector_id":      "ID коннектора",
		"events.filter.action":            "Действие",
		"events.filter.search":            "Поиск по деталям",
		"events.filter.date_from":         "Дата от",
		"events.filter.date_to":           "Дата до",
		"events.filter.sort_by":           "Сортировка по",
		"events.filter.sort_dir":          "Направление",
		"events.filter.page_size":         "Размер страницы",
		"events.actor_type.all":           "Все",
		"events.actor_type.user":          "Пользователь",
		"events.actor_type.admin":         "Админ",
		"events.actor_type.app":           "Приложение",
		"events.sort.created_at":          "время",
		"events.sort.actor_type":          "источник",
		"events.sort.target_user_id":      "ID пользователя мессенджера",
		"events.sort.connector_id":        "ID коннектора",
		"events.sort.action":              "действие",
		"events.sort.asc":                 "по возрастанию",
		"events.sort.desc":                "по убыванию",

		"events.table.time":           "Время",
		"events.table.actor":          "Источник",
		"events.table.actor_user":     "ID пользователя источника",
		"events.table.actor_account":  "Аккаунт источника",
		"events.table.actor_subject":  "Субъект источника",
		"events.table.target_user":    "ID целевого пользователя",
		"events.table.target_account": "Целевой аккаунт",
		"events.table.connector":      "Коннектор",
		"events.table.action":         "Действие",
		"events.table.details":        "Детали",

		"billing.title":                              "Платежи и подписки",
		"billing.subtitle":                           "Операционный срез по оплатам и выданным подпискам.",
		"billing.load_error":                         "не удалось загрузить платежи/подписки",
		"billing.apply":                              "Применить",
		"billing.reset":                              "Сброс",
		"billing.filter.user_id":                     "ID пользователя",
		"billing.filter.telegram_id":                 "Telegram ID (устар.)",
		"billing.filter.connector_id":                "ID коннектора",
		"billing.filter.payment_status":              "Статус платежа",
		"billing.filter.subscription_status":         "Статус подписки",
		"billing.filter.date_from":                   "Дата от",
		"billing.filter.date_to":                     "Дата до",
		"billing.payment_status.any":                 "Любой",
		"billing.payment_status.pending":             "ожидает",
		"billing.payment_status.paid":                "оплачен",
		"billing.payment_status.failed":              "ошибка",
		"billing.sub_status.any":                     "Любой",
		"billing.sub_status.active":                  "активна",
		"billing.sub_status.expired":                 "истекла",
		"billing.sub_status.revoked":                 "отключена",
		"billing.payments.title":                     "Платежи",
		"billing.subscriptions.title":                "Подписки",
		"billing.summary.title":                      "Сводка по выборке",
		"billing.summary.paid_amount":                "Оплачено",
		"billing.summary.pending_amount":             "Ожидает оплаты",
		"billing.summary.paid_payments":              "Успешных платежей",
		"billing.summary.failed_payments":            "Ошибок оплаты",
		"billing.summary.active_subscriptions":       "Активных подписок",
		"billing.groups.title":                       "Итоги по коннекторам",
		"billing.groups.connector":                   "Коннектор",
		"billing.groups.paid_amount":                 "Оплачено",
		"billing.groups.paid_count":                  "Успешно",
		"billing.groups.pending_count":               "В ожидании",
		"billing.groups.failed_count":                "Ошибки",
		"billing.groups.active_subscriptions":        "Активных подписок",
		"churn.title":                                "Проблемные подписки и оплаты",
		"churn.subtitle":                             "Операционный список пользователей, у которых не прошла оплата, истек доступ или подписка требует ручного внимания.",
		"churn.filter.user_id":                       "ID пользователя",
		"churn.filter.issue_type":                    "Тип проблемы",
		"churn.filter.autopay":                       "Автоплатеж",
		"churn.filter.retry_state":                   "Состояние повторов",
		"churn.filter.search":                        "Поиск",
		"churn.filter.search_ph":                     "username, ФИО, email, телефон, коннектор",
		"churn.filter.any":                           "Любой",
		"churn.filter.retry_failed_some":             "ошибки 1-2",
		"churn.filter.retry_exhausted":               "ошибки 3/3",
		"churn.issue.any":                            "Любой",
		"churn.issue.failed_payment":                 "Ошибка оплаты",
		"churn.issue.expired_subscription":           "Истекшая подписка",
		"churn.issue.revoked_subscription":           "Отключенная подписка",
		"churn.issue.pending_payment":                "Ожидающий платеж",
		"churn.table.user":                           "Пользователь",
		"churn.table.connector":                      "Коннектор",
		"churn.table.issue":                          "Проблема",
		"churn.table.autopay":                        "Автоплатеж",
		"churn.table.retry":                          "Повторы",
		"churn.table.payment":                        "Платеж",
		"churn.table.subscription":                   "Подписка",
		"churn.table.amount":                         "Сумма",
		"churn.table.last_event":                     "Последнее событие",
		"churn.table.actions":                        "Действия",
		"churn.recurring.disabled":                   "выключен",
		"churn.recurring.pending":                    "ожидает результат",
		"churn.recurring.not_started":                "попыток не было",
		"churn.recurring.failed_n":                   "ошибок: %d/3",
		"billing.table.payment.id":                   "ID",
		"billing.table.payment.provider":             "Провайдер",
		"billing.table.payment.status":               "Статус",
		"billing.table.payment.autopay":              "Автоплатеж",
		"billing.table.payment.user_id":              "ID пользователя",
		"billing.table.payment.primary_account":      "Основной мессенджер",
		"billing.table.payment.connector":            "Коннектор",
		"billing.table.payment.amount":               "Сумма",
		"billing.table.payment.access":               "Доступ",
		"billing.table.payment.created":              "Создан",
		"billing.table.payment.paid_at":              "Оплачен",
		"billing.table.subscription.id":              "ID",
		"billing.table.subscription.status":          "Статус",
		"billing.table.subscription.autopay":         "Автоплатеж",
		"billing.table.subscription.user_id":         "ID пользователя",
		"billing.table.subscription.primary_account": "Основной мессенджер",
		"billing.table.subscription.connector":       "Коннектор",
		"billing.table.subscription.payment":         "Платеж",
		"billing.table.subscription.access":          "Доступ / отзыв",
		"billing.table.subscription.starts":          "Начало",
		"billing.table.subscription.ends":            "Окончание",
		"billing.table.subscription.created":         "Создана",

		"users.title":                                "Пользователи",
		"users.subtitle":                             "Реестр пользователей, собранных ботом во время регистрации и оплат.",
		"users.load_error":                           "не удалось загрузить пользователей",
		"users.apply":                                "Применить",
		"users.reset":                                "Сброс",
		"common.open":                                "Открыть",
		"common.messenger.telegram":                  "Telegram",
		"common.messenger.max":                       "MAX",
		"users.filter.user_id":                       "ID пользователя",
		"users.filter.telegram_id":                   "Telegram ID (устар.)",
		"users.filter.search":                        "Поиск",
		"users.filter.search_ph":                     "username, ФИО, email, телефон",
		"users.table.user_id":                        "ID пользователя",
		"users.table.profile":                        "Профиль",
		"users.table.primary_account":                "Основной мессенджер",
		"users.table.linked_accounts":                "Связанные аккаунты",
		"users.table.telegram_id":                    "Telegram ID",
		"users.table.telegram_username":              "Telegram username",
		"users.table.full_name":                      "ФИО",
		"users.table.phone":                          "Телефон",
		"users.table.email":                          "Email",
		"users.table.autopay":                        "Автоплатеж",
		"users.table.updated":                        "Обновлен",
		"users.autopay.enabled":                      "включен",
		"users.autopay.disabled":                     "выключен",
		"users.autopay.not_configured":               "не настроен",
		"users.detail.back":                          "Назад к списку",
		"users.detail.profile":                       "Профиль",
		"users.detail.payments":                      "Платежи",
		"users.detail.subscriptions":                 "Подписки",
		"users.detail.consents":                      "Согласия",
		"users.detail.recurring_consents":            "Согласия на автосписания",
		"users.detail.events":                        "События",
		"users.detail.primary_account":               "Основной мессенджер",
		"users.detail.linked_accounts":               "Связанные аккаунты",
		"users.detail.load_error":                    "не удалось загрузить карточку пользователя",
		"users.detail.not_found":                     "пользователь не найден",
		"users.detail.invalid_id":                    "некорректный идентификатор пользователя",
		"users.detail.empty":                         "данных пока нет",
		"users.revoke.action":                        "Действие",
		"users.revoke.button":                        "Отключить",
		"users.revoke.confirm":                       "Отключить подписку пользователю вручную?",
		"users.revoke.success":                       "подписка отключена вручную",
		"users.revoke.failed":                        "не удалось отключить подписку",
		"users.revoke.not_found":                     "подписка не найдена",
		"users.revoke.only_active":                   "вручную можно отключить только активную подписку",
		"users.revoke.notify":                        "Подписка была отключена администратором.",
		"users.revoke.notify_with_connector":         "Подписка «%s» была отключена администратором.",
		"users.revoke.renew":                         "Оформить заново",
		"users.actions.title":                        "Действия",
		"users.actions.message":                      "Сообщение пользователю",
		"users.actions.message_ph":                   "Введите текст, который нужно отправить пользователю",
		"users.actions.message_send":                 "Отправить сообщение",
		"users.actions.message_target":               "Доставка пойдет в:",
		"users.actions.message_open_max_chat":        "Открыть чат в MAX",
		"users.actions.message_copy_open_max":        "Скопировать текст и открыть",
		"users.actions.message_max_compose_hint":     "Если нужен ручной режим отправки в MAX, введите текст здесь и откройте чат бота. Кнопка рядом скопирует текст в буфер и сразу откроет MAX.",
		"users.actions.message_max_compose_copied":   "Текст скопирован. MAX открыт в новой вкладке.",
		"users.actions.message_max_compose_opened":   "MAX открыт. Скопируйте текст вручную, если это требуется браузером.",
		"users.actions.message_unavailable":          "Прямая отправка недоступна: у пользователя нет связанного мессенджера для доставки.",
		"users.actions.paylink":                      "Ссылка на оплату",
		"users.actions.paylink_send":                 "Отправить ссылку",
		"users.actions.message_empty":                "сообщение не должно быть пустым",
		"users.actions.message_sent":                 "сообщение отправлено пользователю",
		"users.actions.paylink_sent":                 "ссылка на оплату отправлена пользователю",
		"users.actions.paylink_unavailable":          "для этой подписки недоступна ссылка на оплату",
		"users.actions.paylink_text":                 "Чтобы продлить или оформить доступ заново, нажмите кнопку ниже.",
		"users.actions.paylink_text_named":           "Чтобы продлить подписку «%s» или оформить ее заново, нажмите кнопку ниже.",
		"users.actions.paylink_max_fallback":         "Если deeplink не откроется, отправьте боту команду: %s",
		"users.actions.paylink_button":               "Оплатить подписку",
		"users.actions.paylink_hint":                 "Кнопка отправки ссылки доступна в таблице подписок для каждого конкретного коннектора.",
		"users.actions.autopay_cancel_page":          "Открыть страницу отключения",
		"users.actions.autopay_cancel_hint":          "Публичная страница без авторизации. Ее можно открыть для проверки UX и использовать для скриншота отмены автоплатежа.",
		"users.actions.autopay_cancel_transport":     "Текущая публичная страница отмены доступна только для",
		"users.actions.rebill_send":                  "Запустить rebill",
		"users.actions.rebill_sent":                  "rebill запущен",
		"users.actions.rebill_existing":              "rebill уже ожидает результата",
		"users.actions.rebill_unavailable":           "rebill недоступен для этой подписки",
		"users.consents.offer_accepted":              "Оферта принята",
		"users.consents.offer_version":               "Версия оферты",
		"users.consents.privacy_accepted":            "Политика принята",
		"users.consents.privacy_version":             "Версия политики",
		"users.consents.custom":                      "внешняя ссылка / custom",
		"users.consents.version_prefix":              "версия",
		"users.recurring_consents.accepted_at":       "Принято",
		"users.recurring_consents.offer_version":     "Оферта",
		"users.recurring_consents.agreement_version": "Соглашение",
		"users.recurring.summary_title":              "Сводка по автоплатежу",
		"users.recurring.summary_status":             "Статус автоплатежа",
		"users.recurring.summary_last_at":            "Последний opt-in",
		"users.recurring.summary_last_connector":     "Последний коннектор",
		"users.recurring.summary_health":             "Состояние",
		"users.recurring.summary_rebill":             "Последний rebill",
		"users.recurring.summary_rebill_at":          "Время попытки",
		"users.recurring.summary_failed_attempts":    "Ошибок подряд",
		"users.recurring.health_no_consent":          "согласий нет",
		"users.recurring.health_missing_consent":     "включен без consent",
		"users.recurring.health_consistent":          "данные консистентны",
		"users.recurring.health_disabled":            "отключен пользователем",
		"users.recurring.rebill_none":                "попыток не было",
		"users.recurring.rebill_pending":             "ожидает результат",
		"users.recurring.rebill_failed":              "последний rebill с ошибкой",
		"users.recurring.rebill_failed_exhausted":    "лимит попыток исчерпан",
		"users.recurring.rebill_paid":                "успешно продлен",

		"guide.title":    "Гайд по админке",
		"guide.subtitle": "Краткие правила по созданию коннекторов, настройке периода и проверке запуска в Telegram и MAX.",
		"guide.s1":       "1. Как создать коннектор",
		"guide.s1.p":     "Заполните название, цену, тип периода и ссылку на канал. ID чата и код запуска нужны только для специальных сценариев.",
		"guide.s2":       "2. Поля формы",
		"guide.s2.p1":    "Название: имя тарифа, которое увидит пользователь.",
		"guide.s2.p2":    "Ссылка на канал: основная публичная ссылка на канал или чат. Для MAX это обычно главное поле.",
		"guide.s2.p3":    "Цена: сумма оплаты в рублях.",
		"guide.s2.p4":    "Тип периода: длительность, календарные месяцы или фиксированная дата. Для автоплатежа подходят длительность и календарные месяцы.",
		"guide.s2.p5":    "Значение периода / месяцы / дата окончания: конкретный срок для выбранного типа периода.",
		"guide.s2.p6":    "Код запуска: команда вида /start ... . Если поле пустое, код будет создан автоматически.",
		"guide.s2.p7":    "Ссылка оферты, ссылка политики и описание: юридические и вспомогательные поля, они скрыты в дополнительных настройках.",
		"guide.s2.p8":    "ID чата: техническое поле. Используйте его только когда сценарий действительно требует явного ID канала или чата.",
		"guide.s3":       "3. Как тестировать",
		"guide.s3.p1":    "Откройте блок запуска в таблице и используйте ссылку для Telegram или MAX. Для MAX также доступна команда /start <код_запуска>.",
		"guide.s3.p2":    "Для коротких проверок автоплатежа используйте длительность в секундах или минутах. Тариф с фиксированной датой в автоплатеже не участвует.",
	},
	langEN: {
		"nav.connectors":    "Connectors",
		"nav.legal":         "Legal",
		"nav.users":         "Users",
		"nav.billing":       "Billing",
		"nav.churn":         "Churn",
		"nav.events":        "Events",
		"nav.sessions":      "Sessions",
		"nav.guide":         "Guide",
		"nav.logout":        "Logout",
		"lang.ru":           "Rus",
		"lang.en":           "Eng",
		"common.export_csv": "Export CSV",
		"common.filters":    "Filters",
		"common.hint":       "Hint",
		"common.summary":    "Summary",
		"common.breakdown":  "Breakdown",
		"common.registry":   "Registry",
		"common.operations": "Operations",
		"common.security":   "Security",
		"common.versioning": "Versioning",
		"common.catalogue":  "Catalogue",
		"common.audit":      "Audit",
		"common.contacts":   "Contacts",
		"common.access":     "Access",
		"common.money":      "Payments",
		"common.legal":      "Legal",
		"common.autopay":    "Autopay",

		"legal.title":                  "Legal documents",
		"legal.subtitle":               "Versioned legal documents used during onboarding and checkout. Each version has its own public URL without auth; if connector links are empty, bot falls back to active documents from this registry.",
		"legal.create":                 "New document version",
		"legal.edit":                   "Edit document",
		"legal.create_button":          "Save version",
		"legal.update_button":          "Save changes",
		"legal.cancel_edit":            "Cancel",
		"legal.table_title":            "Documents registry",
		"legal.public.offer":           "Public offer URL",
		"legal.public.privacy":         "Public privacy URL",
		"legal.public.agreement":       "Public agreement URL",
		"legal.required":               "Required: document type, title, and at least one of Content / External URL.",
		"legal.created":                "document version created",
		"legal.updated":                "document updated",
		"legal.enabled":                "document enabled",
		"legal.disabled":               "document disabled",
		"legal.deleted":                "document deleted",
		"legal.bad_form":               "failed to parse document form",
		"legal.invalid_id":             "invalid document ID",
		"legal.load_error":             "failed to load legal documents",
		"legal.validation.type":        "document type is required",
		"legal.validation.title":       "document title is required",
		"legal.validation.content":     "either document content or external URL is required",
		"legal.type.offer":             "Public offer",
		"legal.type.privacy":           "Privacy policy",
		"legal.type.user_agreement":    "User agreement",
		"legal.form.type":              "Document type *",
		"legal.form.title":             "Title *",
		"legal.form.title_ph":          "For example, Public offer dated 2026-03-20",
		"legal.form.external_url":      "External URL",
		"legal.form.external_url_hint": "If filled, public document page redirects users to this external URL. If empty, users see the saved document text.",
		"legal.form.content":           "Document content",
		"legal.form.content_ph":        "Leave empty if users should be redirected to External URL.",
		"legal.form.is_active":         "Enable document immediately",
		"legal.table.id":               "ID",
		"legal.table.type":             "Type",
		"legal.table.version":          "Version",
		"legal.table.title":            "Title",
		"legal.table.preview":          "Preview",
		"legal.table.source":           "Source",
		"legal.table.active":           "Status",
		"legal.table.created":          "Created",
		"legal.table.actions":          "Actions",
		"legal.table.open":             "Open",
		"legal.table.edit":             "Edit",
		"legal.table.enable":           "Enable",
		"legal.table.disable":          "Disable",
		"legal.table.delete":           "Delete",
		"legal.delete_confirm":         "Delete document? This action cannot be undone.",

		"login.title":               "Admin login",
		"login.subtitle":            "Enter ADMIN_AUTH_TOKEN to access admin panel.",
		"login.token":               "Token",
		"login.submit":              "Sign in",
		"login.hint":                "For local development use ADMIN_AUTH_TOKEN value from .env.",
		"login.bad_form":            "failed to parse form",
		"login.bad_token":           "invalid token",
		"login.rate_limited":        "too many failed attempts, try again later",
		"sessions.title":            "Active sessions",
		"sessions.subtitle":         "Operational list of browser admin sessions. Suspicious or stale sessions can be revoked manually.",
		"sessions.current":          "current",
		"sessions.revoke":           "Revoke",
		"sessions.revoked":          "session revoked",
		"sessions.load_error":       "failed to load sessions",
		"sessions.invalid_id":       "invalid session ID",
		"sessions.status.active":    "active",
		"sessions.status.revoked":   "revoked",
		"sessions.status.expired":   "expired",
		"sessions.table.id":         "ID",
		"sessions.table.subject":    "Subject",
		"sessions.table.ip":         "IP",
		"sessions.table.user_agent": "User-Agent",
		"sessions.table.created":    "Created",
		"sessions.table.expires":    "Expires",
		"sessions.table.last_seen":  "Last seen",
		"sessions.table.status":     "Status",
		"sessions.table.actions":    "Actions",
		"csrf.invalid":              "form session expired, refresh page and try again",

		"connectors.title":                     "Connectors",
		"connectors.subtitle":                  "Connector defines tariff/payment conditions used in bot deep links.",
		"connectors.create":                    "Create connector",
		"connectors.hint_title":                "Hint",
		"connectors.table_title":               "Connectors list",
		"connectors.required":                  "Required: Name, Price RUB. Fill at least one of Chat ID / Channel URL.",
		"connectors.created":                   "connector created",
		"connectors.updated":                   "connector status updated",
		"connectors.deleted":                   "connector deleted",
		"connectors.bad_form":                  "failed to parse form",
		"connectors.invalid_id":                "invalid connector ID",
		"connectors.not_found":                 "connector not found",
		"connectors.delete_in_use":             "connector cannot be deleted because it already has payment, subscription or registration history",
		"connectors.delete_confirm":            "Delete connector? This action cannot be undone.",
		"connector.validation.price":           "price must be a positive number",
		"connector.validation.period_mode":     "period type is required",
		"connector.validation.period_duration": "duration must use a format like 90s, 15m, 12h or 30d",
		"connector.validation.period_months":   "months must be a positive number",
		"connector.validation.period_deadline": "deadline must be in the future and use a valid date/time format",
		"connector.validation.chat_or_url":     "at least one destination is required: Telegram Chat ID, MAX Chat ID, Telegram Channel URL or MAX Channel URL",

		"connectors.form.name":                        "Name *",
		"connectors.form.chat_id":                     "Telegram Chat ID",
		"connectors.form.max_chat_id":                 "MAX Chat ID",
		"connectors.form.price_rub":                   "Price RUB *",
		"connectors.form.period_mode":                 "Period type",
		"connectors.form.period_mode_duration":        "Duration",
		"connectors.form.period_mode_calendar_months": "Calendar months",
		"connectors.form.period_mode_fixed_deadline":  "Fixed deadline",
		"connectors.form.period_value":                "Duration",
		"connectors.form.period_value_hint":           "Examples: 120s, 15m, 12h, 30d.",
		"connectors.form.period_months":               "Months count",
		"connectors.form.period_months_hint":          "Examples: 1, 3, 12.",
		"connectors.form.fixed_ends_at":               "Ends at",
		"connectors.form.fixed_ends_at_hint":          "Absolute access deadline. Recurring is disabled for this kind of connector.",
		"connectors.form.start_payload":               "Start payload",
		"connectors.form.internal_id":                 "Internal ID",
		"connectors.form.offer_url":                   "Offer URL",
		"connectors.form.privacy_url":                 "Privacy URL",
		"connectors.form.channel_url":                 "Telegram Channel URL",
		"connectors.form.max_channel_url":             "MAX Channel URL",
		"connectors.form.description":                 "Description",
		"connectors.form.description_ph":              "Short tariff description",
		"connectors.form.price_ph":                    "3335",
		"connectors.form.channel_hint":                "Public link or @username used for Telegram access after payment.",
		"connectors.form.max_chat_id_hint":            "Explicit MAX chat ID for automatic member remove/regrant. If empty, the app will try to parse it from MAX Channel URL.",
		"connectors.form.max_channel_hint":            "Public MAX destination shown to MAX users after payment.",
		"connectors.form.advanced":                    "Additional settings",
		"connectors.form.advanced_hint":               "Technical and less frequently used fields: Chat ID, payload, legal links, description.",
		"connectors.form.preview":                     "Launch preview",
		"connectors.form.preview_pending":             "If payload is empty, it will be generated automatically on save.",
		"connectors.form.preview_command":             "MAX command",
		"connectors.form.payload_hint":                "Auto-generated if empty.",
		"connectors.form.id_hint":                     "Auto-generated if empty.",
		"connectors.required_short":                   "Required: Name, Price RUB. Fill at least one destination: Telegram Chat ID, MAX Chat ID, Telegram Channel URL or MAX Channel URL.",

		"connectors.table.id":                "ID",
		"connectors.table.payload":           "Payload",
		"connectors.table.name":              "Name",
		"connectors.table.chat":              "Telegram Chat",
		"connectors.table.max_chat_id":       "MAX Chat ID",
		"connectors.table.price":             "Price",
		"connectors.table.period":            "Period",
		"connectors.table.offer":             "Offer",
		"connectors.table.privacy":           "Privacy",
		"connectors.table.channel":           "Destinations",
		"connectors.table.telegram_channel":  "Telegram",
		"connectors.table.max_channel":       "MAX",
		"connectors.table.legal":             "Legal",
		"connectors.table.launch":            "Launch",
		"connectors.table.bot_link":          "Launch links",
		"connectors.table.telegram_bot_link": "Telegram",
		"connectors.table.max_bot_link":      "MAX",
		"connectors.table.max_start_command": "MAX command",
		"connectors.table.open_link":         "Open",
		"connectors.table.bot_open":          "Launch",
		"connectors.table.active":            "Status",
		"connectors.table.action":            "Action",
		"connectors.table.enable":            "Enable",
		"connectors.table.disable":           "Disable",
		"connectors.table.delete":            "Delete",
		"badge.connector.active":             "active",
		"badge.connector.inactive":           "disabled",
		"badge.payment.pending":              "pending",
		"badge.payment.paid":                 "paid",
		"badge.payment.failed":               "failed",
		"badge.subscription.active":          "active",
		"badge.subscription.future":          "next period",
		"badge.subscription.expired":         "expired",
		"badge.subscription.revoked":         "revoked",
		"badge.autopay.enabled":              "enabled",
		"badge.autopay.disabled":             "disabled",
		"badge.autopay.unset":                "not configured",
		"badge.ops.access_ready":             "access ready",
		"badge.ops.access_issue":             "access issue",
		"badge.ops.next_period":              "starts later",
		"badge.ops.not_checked":              "needs check",
		"badge.ops.not_applicable":           "n/a",
		"badge.ops.retry_scheduled":          "retry scheduled",
		"badge.ops.manual_check":             "manual check",
		"badge.ops.revoked":                  "removed from chat",
		"badge.ops.replacement_active":       "renewed already",

		"events.title":      "Audit events",
		"events.subtitle":   "Filter, sort and paginate user actions.",
		"events.load_error": "failed to load events",
		"events.apply":      "Apply",
		"events.reset":      "Reset",
		"events.filter.any": "Any",
		"events.total":      "Total",
		"events.page":       "Page",
		"events.first":      "First",
		"events.prev":       "Prev",
		"events.next":       "Next",
		"events.last":       "Last",

		"events.filter.messenger_kind":    "Messenger",
		"events.filter.actor_type":        "Actor",
		"events.filter.messenger_user_id": "Messenger User ID",
		"events.filter.connector_id":      "Connector ID",
		"events.filter.action":            "Action",
		"events.filter.search":            "Search in details",
		"events.filter.date_from":         "Date from",
		"events.filter.date_to":           "Date to",
		"events.filter.sort_by":           "Sort by",
		"events.filter.sort_dir":          "Sort dir",
		"events.filter.page_size":         "Page size",
		"events.actor_type.all":           "All",
		"events.actor_type.user":          "User",
		"events.actor_type.admin":         "Admin",
		"events.actor_type.app":           "App",
		"events.sort.created_at":          "created_at",
		"events.sort.actor_type":          "actor_type",
		"events.sort.target_user_id":      "messenger_user_id",
		"events.sort.connector_id":        "connector_id",
		"events.sort.action":              "action",
		"events.sort.asc":                 "ascending",
		"events.sort.desc":                "descending",

		"events.table.time":           "Time",
		"events.table.actor":          "Actor",
		"events.table.actor_user":     "Actor User ID",
		"events.table.actor_account":  "Actor account",
		"events.table.actor_subject":  "Actor subject",
		"events.table.target_user":    "Target User ID",
		"events.table.target_account": "Target account",
		"events.table.connector":      "Connector",
		"events.table.action":         "Action",
		"events.table.details":        "Details",

		"billing.title":                              "Payments and subscriptions",
		"billing.subtitle":                           "Operational view of payment attempts and granted subscriptions.",
		"billing.load_error":                         "failed to load payments/subscriptions",
		"billing.apply":                              "Apply",
		"billing.reset":                              "Reset",
		"billing.filter.user_id":                     "User ID",
		"billing.filter.telegram_id":                 "Telegram ID (legacy)",
		"billing.filter.connector_id":                "Connector ID",
		"billing.filter.payment_status":              "Payment status",
		"billing.filter.subscription_status":         "Subscription status",
		"billing.filter.date_from":                   "Date from",
		"billing.filter.date_to":                     "Date to",
		"billing.payment_status.any":                 "Any",
		"billing.payment_status.pending":             "pending",
		"billing.payment_status.paid":                "paid",
		"billing.payment_status.failed":              "failed",
		"billing.sub_status.any":                     "Any",
		"billing.sub_status.active":                  "active",
		"billing.sub_status.expired":                 "expired",
		"billing.sub_status.revoked":                 "revoked",
		"billing.payments.title":                     "Payments",
		"billing.subscriptions.title":                "Subscriptions",
		"billing.summary.title":                      "Selection summary",
		"billing.summary.paid_amount":                "Paid amount",
		"billing.summary.pending_amount":             "Pending amount",
		"billing.summary.paid_payments":              "Successful payments",
		"billing.summary.failed_payments":            "Failed payments",
		"billing.summary.active_subscriptions":       "Active subscriptions",
		"billing.groups.title":                       "Connector totals",
		"billing.groups.connector":                   "Connector",
		"billing.groups.paid_amount":                 "Paid amount",
		"billing.groups.paid_count":                  "Successful",
		"billing.groups.pending_count":               "Pending",
		"billing.groups.failed_count":                "Failed",
		"billing.groups.active_subscriptions":        "Active subscriptions",
		"churn.title":                                "Subscription and payment issues",
		"churn.subtitle":                             "Operational list of users with failed payments, expired access, or subscriptions that require manual attention.",
		"churn.filter.user_id":                       "User ID",
		"churn.filter.issue_type":                    "Issue type",
		"churn.filter.autopay":                       "Autopay",
		"churn.filter.retry_state":                   "Retry state",
		"churn.filter.search":                        "Search",
		"churn.filter.search_ph":                     "username, full name, email, phone, connector",
		"churn.filter.any":                           "Any",
		"churn.filter.retry_failed_some":             "failures 1-2",
		"churn.filter.retry_exhausted":               "failures 3/3",
		"churn.issue.any":                            "Any",
		"churn.issue.failed_payment":                 "Failed payment",
		"churn.issue.expired_subscription":           "Expired subscription",
		"churn.issue.revoked_subscription":           "Revoked subscription",
		"churn.issue.pending_payment":                "Pending payment",
		"churn.table.user":                           "User",
		"churn.table.connector":                      "Connector",
		"churn.table.issue":                          "Issue",
		"churn.table.autopay":                        "Autopay",
		"churn.table.retry":                          "Retry",
		"churn.table.payment":                        "Payment",
		"churn.table.subscription":                   "Subscription",
		"churn.table.amount":                         "Amount",
		"churn.table.last_event":                     "Last event",
		"churn.table.actions":                        "Actions",
		"churn.recurring.disabled":                   "disabled",
		"churn.recurring.pending":                    "awaiting result",
		"churn.recurring.not_started":                "no attempts yet",
		"churn.recurring.failed_n":                   "failures: %d/3",
		"billing.table.payment.id":                   "ID",
		"billing.table.payment.provider":             "Provider",
		"billing.table.payment.status":               "Status",
		"billing.table.payment.autopay":              "Autopay",
		"billing.table.payment.user_id":              "User ID",
		"billing.table.payment.primary_account":      "Primary messenger",
		"billing.table.payment.connector":            "Connector",
		"billing.table.payment.amount":               "Amount",
		"billing.table.payment.access":               "Access",
		"billing.table.payment.created":              "Created",
		"billing.table.payment.paid_at":              "Paid at",
		"billing.table.subscription.id":              "ID",
		"billing.table.subscription.status":          "Status",
		"billing.table.subscription.autopay":         "Autopay",
		"billing.table.subscription.user_id":         "User ID",
		"billing.table.subscription.primary_account": "Primary messenger",
		"billing.table.subscription.connector":       "Connector",
		"billing.table.subscription.payment":         "Payment",
		"billing.table.subscription.access":          "Access / revoke",
		"billing.table.subscription.starts":          "Starts",
		"billing.table.subscription.ends":            "Ends",
		"billing.table.subscription.created":         "Created",

		"users.title":                                "Users",
		"users.subtitle":                             "Registry of users collected by the bot during registration and payments.",
		"users.load_error":                           "failed to load users",
		"users.apply":                                "Apply",
		"users.reset":                                "Reset",
		"common.open":                                "Open",
		"common.messenger.telegram":                  "Telegram",
		"common.messenger.max":                       "MAX",
		"users.filter.user_id":                       "User ID",
		"users.filter.telegram_id":                   "Telegram ID (legacy)",
		"users.filter.search":                        "Search",
		"users.filter.search_ph":                     "username, full name, email, phone",
		"users.table.user_id":                        "User ID",
		"users.table.profile":                        "Profile",
		"users.table.primary_account":                "Primary messenger",
		"users.table.linked_accounts":                "Linked accounts",
		"users.table.telegram_id":                    "Telegram ID",
		"users.table.telegram_username":              "Telegram username",
		"users.table.full_name":                      "Full name",
		"users.table.phone":                          "Phone",
		"users.table.email":                          "E-mail",
		"users.table.autopay":                        "Autopay",
		"users.table.updated":                        "Updated",
		"users.autopay.enabled":                      "enabled",
		"users.autopay.disabled":                     "disabled",
		"users.autopay.not_configured":               "not configured",
		"users.detail.back":                          "Back to list",
		"users.detail.profile":                       "Profile",
		"users.detail.payments":                      "Payments",
		"users.detail.subscriptions":                 "Subscriptions",
		"users.detail.consents":                      "Consents",
		"users.detail.recurring_consents":            "Recurring consents",
		"users.detail.events":                        "Events",
		"users.detail.primary_account":               "Primary messenger",
		"users.detail.linked_accounts":               "Linked accounts",
		"users.detail.load_error":                    "failed to load user card",
		"users.detail.not_found":                     "user not found",
		"users.detail.invalid_id":                    "invalid user identifier",
		"users.detail.empty":                         "no data yet",
		"users.revoke.action":                        "Action",
		"users.revoke.button":                        "Disable",
		"users.revoke.confirm":                       "Disable this subscription manually?",
		"users.revoke.success":                       "subscription disabled manually",
		"users.revoke.failed":                        "failed to disable subscription",
		"users.revoke.not_found":                     "subscription not found",
		"users.revoke.only_active":                   "only active subscription can be disabled manually",
		"users.revoke.notify":                        "Your subscription was disabled by the administrator.",
		"users.revoke.notify_with_connector":         "Your subscription \"%s\" was disabled by the administrator.",
		"users.revoke.renew":                         "Renew access",
		"users.actions.title":                        "Actions",
		"users.actions.message":                      "Message user",
		"users.actions.message_ph":                   "Enter text to send to the user",
		"users.actions.message_send":                 "Send message",
		"users.actions.message_target":               "Delivery target:",
		"users.actions.message_open_max_chat":        "Open MAX chat",
		"users.actions.message_copy_open_max":        "Copy text and open",
		"users.actions.message_max_compose_hint":     "Use this when you need a manual compose flow inside MAX. Type the message here and open the bot chat. The helper button copies the text and opens MAX immediately.",
		"users.actions.message_max_compose_copied":   "Message copied. MAX opened in a new tab.",
		"users.actions.message_max_compose_opened":   "MAX opened. Copy the message manually if your browser blocks clipboard access.",
		"users.actions.message_unavailable":          "Direct send is unavailable because the user has no linked messenger delivery account.",
		"users.actions.paylink":                      "Payment link",
		"users.actions.paylink_send":                 "Send link",
		"users.actions.message_empty":                "message cannot be empty",
		"users.actions.message_sent":                 "message sent to user",
		"users.actions.paylink_sent":                 "payment link sent to user",
		"users.actions.paylink_unavailable":          "payment link is unavailable for this subscription",
		"users.actions.paylink_text":                 "To renew or purchase access again, use the button below.",
		"users.actions.paylink_text_named":           "To renew subscription \"%s\" or purchase it again, use the button below.",
		"users.actions.paylink_max_fallback":         "If the deeplink does not open, send the bot this command: %s",
		"users.actions.paylink_button":               "Pay subscription",
		"users.actions.paylink_hint":                 "Payment-link sending is available in the subscriptions table for each connector.",
		"users.actions.autopay_cancel_page":          "Open cancel page",
		"users.actions.autopay_cancel_hint":          "Public page without admin auth. Use it to verify UX and capture the recurring cancellation screenshot.",
		"users.actions.autopay_cancel_transport":     "The current public cancellation page is available only for",
		"users.actions.rebill_send":                  "Trigger rebill",
		"users.actions.rebill_sent":                  "rebill started",
		"users.actions.rebill_existing":              "rebill is already pending",
		"users.actions.rebill_unavailable":           "rebill is unavailable for this subscription",
		"users.consents.offer_accepted":              "Offer accepted",
		"users.consents.offer_version":               "Offer version",
		"users.consents.privacy_accepted":            "Privacy accepted",
		"users.consents.privacy_version":             "Privacy version",
		"users.consents.custom":                      "external URL / custom",
		"users.consents.version_prefix":              "version",
		"users.recurring_consents.accepted_at":       "Accepted at",
		"users.recurring_consents.offer_version":     "Offer",
		"users.recurring_consents.agreement_version": "Agreement",
		"users.recurring.summary_title":              "Recurring summary",
		"users.recurring.summary_status":             "Autopay status",
		"users.recurring.summary_last_at":            "Last opt-in",
		"users.recurring.summary_last_connector":     "Last connector",
		"users.recurring.summary_health":             "Health",
		"users.recurring.summary_rebill":             "Last rebill",
		"users.recurring.summary_rebill_at":          "Attempt time",
		"users.recurring.summary_failed_attempts":    "Consecutive failures",
		"users.recurring.health_no_consent":          "no consents",
		"users.recurring.health_missing_consent":     "enabled without consent",
		"users.recurring.health_consistent":          "data is consistent",
		"users.recurring.health_disabled":            "disabled by user",
		"users.recurring.rebill_none":                "no attempts yet",
		"users.recurring.rebill_pending":             "awaiting result",
		"users.recurring.rebill_failed":              "last rebill failed",
		"users.recurring.rebill_failed_exhausted":    "retry limit exhausted",
		"users.recurring.rebill_paid":                "renewed successfully",

		"guide.title":    "Admin guide",
		"guide.subtitle": "Short notes on connector creation, period modes, and Telegram/MAX launch testing.",
		"guide.s1":       "1. How to create connector",
		"guide.s1.p":     "Fill Name, Price RUB, Period mode, and Channel URL. Chat ID and payload are only needed for special scenarios.",
		"guide.s2":       "2. Form fields",
		"guide.s2.p1":    "Name: tariff name visible to users.",
		"guide.s2.p2":    "Channel URL: primary public entry into the channel or chat. For MAX this is usually the main field.",
		"guide.s2.p3":    "Price RUB: payment amount in RUB.",
		"guide.s2.p4":    "Period mode: duration, calendar months, or fixed deadline. Recurring supports duration and calendar months.",
		"guide.s2.p5":    "Duration value / months / fixed ends at: the concrete period value for the selected mode.",
		"guide.s2.p6":    "Start payload: launch token (/start ...). Auto-generated when empty.",
		"guide.s2.p7":    "Offer URL, Privacy URL, and Description: legal/supporting fields grouped under advanced settings.",
		"guide.s2.p8":    "Chat ID: technical field. Use it only when the transport/scenario really needs an explicit chat identifier.",
		"guide.s3":       "3. How to test",
		"guide.s3.p1":    "Open the Launch block in the table and use the Telegram or MAX launch link. MAX also exposes a fallback /start <payload> command.",
		"guide.s3.p2":    "For recurring smoke tests use duration in seconds/minutes. Fixed deadline does not participate in autopay flow.",
	},
}

func (h *Handler) resolveLang(w http.ResponseWriter, r *http.Request) string {
	lang := normalizeLang(r.URL.Query().Get("lang"))
	if lang != "" {
		h.setCookie(w, r, http.Cookie{
			Name:     "admin_lang",
			Value:    lang,
			Path:     "/",
			HttpOnly: false,
			SameSite: http.SameSiteLaxMode,
			MaxAge:   int((30 * 24 * time.Hour).Seconds()),
		})
		return lang
	}
	if c, err := r.Cookie("admin_lang"); err == nil {
		if normalized := normalizeLang(c.Value); normalized != "" {
			return normalized
		}
	}
	return langRU
}

func normalizeLang(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case langEN:
		return langEN
	case langRU:
		return langRU
	default:
		return ""
	}
}

func dictForLang(lang string) map[string]string {
	if d, ok := translations[lang]; ok {
		return d
	}
	return translations[langRU]
}

func t(lang, key string) string {
	d := dictForLang(lang)
	if v, ok := d[key]; ok {
		return v
	}
	if v, ok := translations[langRU][key]; ok {
		return v
	}
	return key
}
